DROP DATABASE IF EXISTS php_zenith_api;
CREATE DATABASE php_zenith_api;
USE php_zenith_api;
SHOW TABLES;
SELECT * FROM orders;
SELECT * FROM product_orders;
SELECT * FROM social_accounts;
SELECT * FROM expedition_cities;
SELECT * FROM addresses;
SELECT * FROM products;
SELECT * FROM carts;
SELECT * FROM users;
SELECT * FROM social_accounts;
SELECT * FROM carts;
SELECT * FROM personal_access_tokens;
SELECT * FROM product_resources;
SELECT * FROM product_categories;
SELECT * FROM product_carts;
SELECT * FROM users;
SHOW CREATE TABLE personal_access_tokens;
SELECT * FROM user_profiles;
UPDATE user_profiles SET email = 'budisaragin@gmail.com' WHERE id = 1;
SELECT * FROM social_accounts;
SELECT * FROM users;
SELECT * FROM stores;
SELECT * FROM categories;
SELECT * FROM expeditions;
SELECT * FROM products;
SELECT * FROM product_orders;
SELECT * FROM expedition_cities;
SELECT * FROM expedition_provinces;
SELECT * FROM expeditions;
