DROP DATABASE IF EXISTS php_zenith_api;
CREATE DATABASE php_zenith_api;
USE php_zenith_api;
SHOW TABLES;
SELECT * FROM social_accounts;
SELECT * FROM users;
SELECT * FROM expedition_cities;
SELECT * FROM addresses;
SELECT * FROM products;
SELECT * FROM carts;
SELECT * FROM users;
SELECT * FROM social_accounts;
SELECT * FROM carts;
SELECT * FROM personal_access_tokens;
UPDATE personal_access_tokens SET token='awdawd' WHERE id=1;
SELECT * FROM product_resources;
SELECT * FROM product_categories;
SHOW CREATE TABLE personal_access_tokens;
